' NOTE: THIS CLASS WAS AI-GENERATED BY CLAUDE (OPUS 4.6)
'
' MODIFICATIONS MAY BE REALIZED IN FUTURE VERSIONS OF THIS APPLICATION TO CLEAN AI ARTIFACTS AND IMPROVE CODE QUALITY,
' BUT NO GUARANTEE IS MADE ON THE MAINTENANCE OF THIS CLASS.

#Region " Option Statements "

Option Strict On
Option Explicit On
Option Infer Off

#End Region

#Region " Imports "

Imports System.ComponentModel
Imports System.Drawing.Design
Imports System.Windows.Forms.Design

Imports DevCase.Core.IO

#End Region

#Region " InstalledAppInfo "

''' 
''' <summary>
''' Represents an installed application entry enumerated from the Windows <c>shell:AppsFolder</c>
''' virtual folder, pairing a display name with an <c>AppUserModelID</c>.
''' </summary>
''' 
Public NotInheritable Class InstalledAppInfo

    ''' 
    ''' <summary>
    ''' Gets the display name of the application as shown in the Start menu.
    ''' </summary>
    ''' 
    Public ReadOnly Property DisplayName As String

    ''' 
    ''' <summary>
    ''' Gets the <c>AppUserModelID</c> of the application.
    ''' </summary>
    ''' 
    Public ReadOnly Property AppUserModelId As String

    ''' 
    ''' <summary>
    ''' Initializes a new instance of the <see cref="InstalledAppInfo"/> class.
    ''' </summary>
    ''' 
    ''' <param name="displayName">
    ''' The display name of the application.
    ''' </param>
    ''' 
    ''' <param name="appUserModelId">
    ''' The <c>AppUserModelID</c> of the application.
    ''' </param>
    ''' 
    Public Sub New(displayName As String, appUserModelId As String)
            Me.DisplayName = displayName
            Me.AppUserModelId = appUserModelId
        End Sub

    ''' 
    ''' <summary>
    ''' Returns a string representation of this <see cref="InstalledAppInfo"/> instance.
    ''' </summary>
    ''' 
    ''' <returns>
    ''' A string in the form <c>DisplayName (AppUserModelId)</c>.
    ''' </returns>
    ''' 
    Public Overrides Function ToString() As String
            Return $"{Me.DisplayName} ({Me.AppUserModelId})"
        End Function

    End Class

#End Region