' NOTE: THIS CLASS WAS AI-GENERATED BY CLAUDE (OPUS 4.6)
'
' MODIFICATIONS MAY BE REALIZED IN FUTURE VERSIONS OF THIS APPLICATION TO CLEAN AI ARTIFACTS AND IMPROVE CODE QUALITY,
' BUT NO GUARANTEE IS MADE ON THE MAINTENANCE OF THIS CLASS.

#Region " Option Statements "

Option Strict On
Option Explicit On
Option Infer Off

#End Region

#Region " Imports "

Imports System.ComponentModel
Imports System.IO
Imports System.Runtime.InteropServices
Imports System.Threading

#End Region

#Region " ShortcutAppIdHelper "

''' 
''' <summary>
''' Provides helper methods to read, write and enumerate <c>AppUserModelID</c> values
''' associated with shortcut (<c>.lnk</c>) files and installed applications.
''' </summary>
''' 
''' <remarks>
''' The <c>AppUserModelID</c> (AUMID) is stored in the shortcut's <c>PropertyStore</c>
''' under the property key <c>PKEY_AppUserModel_ID</c>
''' (<c>{9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3}, 5</c>).
''' <para></para>
''' It is not exposed by the classic <c>IShellLinkW</c> interface and must be accessed through
''' <c>IPropertyStore</c> or <c>IShellItem2</c>.
''' </remarks>
''' 
Public NotInheritable Class ShortcutAppIdHelper

#Region " Private Constructor "

    ''' 
    ''' <summary>
    ''' Prevents a default instance of the <see cref="ShortcutAppIdHelper"/> class from being created.
    ''' </summary>
    ''' 
    Private Sub New()
        End Sub

#End Region

#Region " Interop Types "

        <StructLayout(LayoutKind.Sequential, Pack:=4)>
        Private Structure PropertyKey
            Public FormatId As Guid
            Public PropertyId As Integer

            Public Sub New(formatId As Guid, propertyId As Integer)
                Me.FormatId = formatId
                Me.PropertyId = propertyId
            End Sub
        End Structure

        <StructLayout(LayoutKind.Explicit)>
        Private Structure PropVariantNative
            <FieldOffset(0)> Public vt As UShort
            <FieldOffset(2)> Public wReserved1 As UShort
            <FieldOffset(4)> Public wReserved2 As UShort
            <FieldOffset(6)> Public wReserved3 As UShort
            <FieldOffset(8)> Public pointerValue As IntPtr
        End Structure

        <ComImport>
        <Guid("886D8EEB-8CF2-4446-8D02-CDBA1DBDCF99")>
        <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>
        Private Interface IPropertyStore
            Sub GetCount(<Out> ByRef propertyCount As UInteger)
            Sub GetAt(<[In]> propertyIndex As UInteger, <Out> ByRef key As PropertyKey)
            Sub GetValue(<[In]> ByRef key As PropertyKey, <[In]> pv As IntPtr)
            Sub SetValue(<[In]> ByRef key As PropertyKey, <[In]> ByRef pv As PropVariantNative)
            Sub Commit()
        End Interface

        <ComImport>
        <Guid("886D8EEB-8CF2-4446-8D02-CDBA1DBDCF99")>
        <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>
        Private Interface IPropertyStoreRaw
            Sub GetCount(<Out> ByRef propertyCount As UInteger)
            Sub GetAt(<[In]> propertyIndex As UInteger, <Out> ByRef key As PropertyKey)
            Sub GetValue(<[In]> ByRef key As PropertyKey, <[In]> pv As IntPtr)
            Sub SetValue(<[In]> ByRef key As PropertyKey, <[In]> pv As IntPtr)
            Sub Commit()
        End Interface

        <ComImport>
        <Guid("43826D1E-E718-42EE-BC55-A1E261C37BFE")>
        <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>
        Private Interface IShellItem
            Sub BindToHandler(pbc As IntPtr,
                              <[In]> ByRef bhid As Guid,
                              <[In]> ByRef riid As Guid,
                              <Out, MarshalAs(UnmanagedType.Interface)> ByRef ppv As Object)
            Sub GetParent(<Out, MarshalAs(UnmanagedType.Interface)> ByRef ppsi As IShellItem)
            Sub GetDisplayName(<[In]> sigdnName As UInteger,
                               <Out, MarshalAs(UnmanagedType.LPWStr)> ByRef ppszName As String)
            Sub GetAttributes(<[In]> sfgaoMask As UInteger, <Out> ByRef psfgaoAttribs As UInteger)
            Sub Compare(<[In], MarshalAs(UnmanagedType.Interface)> psi As IShellItem,
                        <[In]> hint As UInteger,
                        <Out> ByRef piOrder As Integer)
        End Interface

        <ComImport>
        <Guid("7E9FB0D3-919F-4307-AB2E-9B1860310C93")>
        <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>
        Private Interface IShellItem2
            ' --- IShellItem methods ---
            Sub BindToHandler(pbc As IntPtr,
                              <[In]> ByRef bhid As Guid,
                              <[In]> ByRef riid As Guid,
                              <Out, MarshalAs(UnmanagedType.Interface)> ByRef ppv As Object)
            Sub GetParent(<Out, MarshalAs(UnmanagedType.Interface)> ByRef ppsi As IShellItem)
            Sub GetDisplayName(<[In]> sigdnName As UInteger,
                               <Out, MarshalAs(UnmanagedType.LPWStr)> ByRef ppszName As String)
            Sub GetAttributes(<[In]> sfgaoMask As UInteger, <Out> ByRef psfgaoAttribs As UInteger)
            Sub Compare(<[In], MarshalAs(UnmanagedType.Interface)> psi As IShellItem,
                        <[In]> hint As UInteger,
                        <Out> ByRef piOrder As Integer)
            ' --- IShellItem2 methods ---
            Sub GetPropertyStore(flags As Integer,
                                 <[In]> ByRef riid As Guid,
                                 <Out, MarshalAs(UnmanagedType.Interface)> ByRef ppv As Object)
            Sub GetPropertyStoreWithCreateObject(flags As Integer,
                                                 <MarshalAs(UnmanagedType.IUnknown)> punkCreateObject As Object,
                                                 <[In]> ByRef riid As Guid,
                                                 <Out> ByRef ppv As IntPtr)
            Sub GetPropertyStoreForKeys(ByRef rgKeys As PropertyKey,
                                        cKeys As UInteger,
                                        flags As Integer,
                                        <[In]> ByRef riid As Guid,
                                        <Out, MarshalAs(UnmanagedType.Interface)> ByRef ppv As Object)
            Sub GetPropertyDescriptionList(<[In]> ByRef keyType As PropertyKey,
                                           <[In]> ByRef riid As Guid,
                                           <Out> ByRef ppv As IntPtr)
            Sub Update(pbc As IntPtr)
            Sub GetProperty(<[In]> ByRef key As PropertyKey, pv As IntPtr)
            Sub GetCLSID(<[In]> ByRef key As PropertyKey, <Out> ByRef pclsid As Guid)
            Sub GetFileTime(<[In]> ByRef key As PropertyKey, <Out> ByRef pft As Long)
            Sub GetInt32(<[In]> ByRef key As PropertyKey, <Out> ByRef pi As Integer)
            Sub GetString(<[In]> ByRef key As PropertyKey,
                          <Out, MarshalAs(UnmanagedType.LPWStr)> ByRef ppsz As String)
            Sub GetUInt32(<[In]> ByRef key As PropertyKey, <Out> ByRef pui As UInteger)
            Sub GetUInt64(<[In]> ByRef key As PropertyKey, <Out> ByRef pull As ULong)
            Sub GetBool(<[In]> ByRef key As PropertyKey, <Out> ByRef pf As Integer)
        End Interface

        <ComImport>
        <Guid("70629033-E363-4A28-A567-0DB78006E6D7")>
        <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>
        Private Interface IEnumShellItems
            <PreserveSig>
            Function [Next](celt As UInteger,
                            <Out, MarshalAs(UnmanagedType.Interface)> ByRef rgelt As IShellItem,
                            <Out> ByRef pceltFetched As UInteger) As Integer
            Sub Skip(celt As UInteger)
            Sub Reset()
            Sub Clone(<Out, MarshalAs(UnmanagedType.Interface)> ByRef ppenum As IEnumShellItems)
        End Interface

        <DllImport("shell32.dll", CharSet:=CharSet.Unicode, PreserveSig:=False)>
        Private Shared Sub SHCreateItemFromParsingName(
            <MarshalAs(UnmanagedType.LPWStr)> pszPath As String,
            pbc As IntPtr,
            <[In]> ByRef riid As Guid,
            <Out, MarshalAs(UnmanagedType.Interface)> ByRef ppv As Object)
        End Sub

        <DllImport("shell32.dll", CharSet:=CharSet.Unicode)>
        Private Shared Function SHGetPropertyStoreFromParsingName(
            <MarshalAs(UnmanagedType.LPWStr)> pszPath As String,
            pbc As IntPtr,
            flags As Integer,
            <[In]> ByRef riid As Guid,
            <Out, MarshalAs(UnmanagedType.Interface)> ByRef ppv As Object) As Integer
        End Function

        <DllImport("ole32.dll")>
        Private Shared Function PropVariantClear(<[In], Out> ByRef pvar As PropVariantNative) As Integer
        End Function

        <DllImport("ole32.dll")>
        Private Shared Function PropVariantCopy(<[In], Out> pvarDest As IntPtr, <[In]> pvarSource As IntPtr) As Integer
        End Function

        <DllImport("ole32.dll", EntryPoint:="PropVariantClear")>
        Private Shared Function PropVariantClearPtr(<[In], Out> pvar As IntPtr) As Integer
        End Function

#End Region

#Region " Interop Constants "

    ''' 
    ''' <summary>
    ''' Property key for <c>System.AppUserModel.ID</c>.
    ''' </summary>
    ''' 
    Private Shared ReadOnly PKEY_AppUserModel_ID As New PropertyKey(New Guid("9F4C2855-9F79-4B39-A8D0-E1D42DE1D5F3"), 5)

        Private Shared ReadOnly IID_IPropertyStore As New Guid("886D8EEB-8CF2-4446-8D02-CDBA1DBDCF99")

        Private Shared ReadOnly IID_IShellItem As New Guid("43826D1E-E718-42EE-BC55-A1E261C37BFE")

        Private Shared ReadOnly IID_IShellItem2 As New Guid("7E9FB0D3-919F-4307-AB2E-9B1860310C93")

        Private Shared ReadOnly IID_IEnumShellItems As New Guid("70629033-E363-4A28-A567-0DB78006E6D7")

    ''' 
    ''' <summary>
    ''' Binding handler id for <c>IEnumShellItems</c>.
    ''' </summary>
    ''' 
    Private Shared ReadOnly BHID_EnumItems As New Guid("94F60519-2850-4924-AA5A-D15E84868039")

    Private Const GPS_READWRITE As Integer = 2
    ' Private Const GPS_NO_OPLOCK As Integer = &H80

    ''' 
    ''' <summary>
    ''' HRESULT returned by <c>IShellItem2.GetString</c> when the requested property is not present.
    ''' </summary>
    ''' 
    Private Const E_ELEMENTNOTFOUND As Integer = &H80070490

#End Region

#Region " Public Methods "

    ''' 
    ''' <summary>
    ''' Reads the <c>AppUserModelID</c> from the specified shortcut (<c>.lnk</c>) file.
    ''' </summary>
    ''' 
    ''' <param name="shortcutPath">
    ''' The full path of the shortcut file.
    ''' </param>
    ''' 
    ''' <returns>
    ''' The <c>AppUserModelID</c> string stored in the shortcut's <c>PropertyStore</c>,
    ''' or <see langword="Nothing"/> if the property is not present.
    ''' </returns>
    ''' 
    ''' <exception cref="ArgumentNullException">
    ''' Thrown if <paramref name="shortcutPath"/> is <see langword="Nothing"/> or an empty string.
    ''' </exception>
    ''' 
    ''' <exception cref="FileNotFoundException">
    ''' Thrown if the specified shortcut file does not exist.
    ''' </exception>
    ''' 
    ''' <exception cref="InvalidOperationException">
    ''' Thrown if the underlying Shell API call fails for an unexpected reason.
    ''' </exception>
    ''' 
    Public Shared Function GetAppUserModelId(shortcutPath As String) As String
            If String.IsNullOrEmpty(shortcutPath) Then
                Throw New ArgumentNullException(NameOf(shortcutPath))
            End If
            If Not File.Exists(shortcutPath) Then
                Throw New FileNotFoundException($"The specified shortcut file is not found: {shortcutPath}", shortcutPath)
            End If

            Dim shellItemObj As Object = Nothing
            Dim shellItem2 As IShellItem2 = Nothing
            Try
                Dim iid As Guid = IID_IShellItem2
                SHCreateItemFromParsingName(shortcutPath, IntPtr.Zero, iid, shellItemObj)
                shellItem2 = DirectCast(shellItemObj, IShellItem2)

                Dim key As PropertyKey = PKEY_AppUserModel_ID
                Dim appId As String = Nothing
                shellItem2.GetString(key, appId)
                Return appId

            Catch comEx As COMException When comEx.ErrorCode = E_ELEMENTNOTFOUND
                ' The property is not set on this shortcut.
                Return Nothing

            Catch ex As Exception
                Throw New InvalidOperationException($"Failed to read AppUserModelID from shortcut: {shortcutPath}", ex)

            Finally
                If shellItem2 IsNot Nothing AndAlso Marshal.IsComObject(shellItem2) Then
                    Marshal.FinalReleaseComObject(shellItem2)
                End If

#Disable Warning IDE0059 ' Unnecessary assignment of a value
                shellItem2 = Nothing
                shellItemObj = Nothing
#Enable Warning IDE0059 ' Unnecessary assignment of a value
                GC.Collect()
                GC.WaitForPendingFinalizers()
                GC.Collect()
            End Try
        End Function

    ''' 
    ''' <summary>
    ''' Writes (or overwrites) the <c>AppUserModelID</c> of the specified shortcut (<c>.lnk</c>) file.
    ''' </summary>
    ''' 
    ''' <param name="shortcutPath">
    ''' The full path of the shortcut file.
    ''' </param>
    ''' 
    ''' <param name="appId">
    ''' The new <c>AppUserModelID</c> to assign to the shortcut.
    ''' </param>
    ''' 
    ''' <exception cref="ArgumentNullException">
    ''' Thrown if <paramref name="shortcutPath"/> or <paramref name="appId"/> is <see langword="Nothing"/>.
    ''' </exception>
    ''' 
    ''' <exception cref="FileNotFoundException">
    ''' Thrown if the specified shortcut file does not exist.
    ''' </exception>
    ''' 
    ''' <exception cref="InvalidOperationException">
    ''' Thrown if the underlying Shell API call fails to commit the new value.
    ''' </exception>
    ''' 
    Public Shared Sub SetAppUserModelId(shortcutPath As String, appId As String)

        If String.IsNullOrEmpty(shortcutPath) Then
            Throw New ArgumentNullException(NameOf(shortcutPath))
        End If
        If appId Is Nothing Then
            Throw New ArgumentNullException(NameOf(appId))
        End If
        If Not File.Exists(shortcutPath) Then
            Throw New FileNotFoundException($"The specified shortcut file is not found: {shortcutPath}", shortcutPath)
        End If

        Dim propertyStoreObj As Object = Nothing
        Dim propertyStore As IPropertyStore = Nothing
        Dim propVariant As New PropVariantNative()
        Dim stringPtr As IntPtr = IntPtr.Zero
        Dim mustFreeString As Boolean = False

        Try
            Dim iid As Guid = IID_IPropertyStore
            Dim hr As Integer = SHGetPropertyStoreFromParsingName(shortcutPath, IntPtr.Zero, GPS_READWRITE, iid, propertyStoreObj)
            If hr <> 0 Then
                Throw New Win32Exception(hr, $"SHGetPropertyStoreFromParsingName failed with HRESULT 0x{hr:X8}.")
            End If

            propertyStore = DirectCast(propertyStoreObj, IPropertyStore)

            ' Manually build a VT_LPWSTR PROPVARIANT.
            stringPtr = Marshal.StringToCoTaskMemUni(appId)
            mustFreeString = True

            propVariant.vt = CUShort(31) ' VT_LPWSTR
            propVariant.wReserved1 = 0US
            propVariant.wReserved2 = 0US
            propVariant.wReserved3 = 0US
            propVariant.pointerValue = stringPtr

            Dim key As PropertyKey = PKEY_AppUserModel_ID
            propertyStore.SetValue(key, propVariant)
            propertyStore.Commit()

            ' After SetValue+Commit succeed, PropVariantClear will release the string buffer.
            Try
                PropVariantClear(propVariant)
                mustFreeString = False
            Catch
                ' Fallback: free manually in the Finally block below.
            End Try

        Catch ex As Exception
            Throw New InvalidOperationException($"Failed to write AppUserModelID to shortcut: {shortcutPath}", ex)

        Finally
            If mustFreeString AndAlso stringPtr <> IntPtr.Zero Then
                Marshal.FreeCoTaskMem(stringPtr)
            End If
            If propertyStore IsNot Nothing AndAlso Marshal.IsComObject(propertyStore) Then
                Marshal.FinalReleaseComObject(propertyStore)
            End If

#Disable Warning IDE0059 ' Unnecessary assignment of a value
            propertyStore = Nothing
            propertyStoreObj = Nothing
#Enable Warning IDE0059 ' Unnecessary assignment of a value
            ' Force the Shell's property handler to release its internal file handle.
            ' Without this, a subsequent File.SetCreationTime / etc. on the same path
            ' throws IOException "file is being used by another process".
            GC.Collect()
            GC.WaitForPendingFinalizers()
            GC.Collect()
        End Try
    End Sub

    ''' <summary>
    ''' Removes the <c>AppUserModelID</c> property from the specified shortcut (<c>.lnk</c>) file,
    ''' if present.
    ''' </summary>
    ''' 
    ''' <param name="shortcutPath">
    ''' The full path of the shortcut file.
    ''' </param>
    ''' 
    ''' <exception cref="ArgumentNullException">
    ''' Thrown if <paramref name="shortcutPath"/> is <see langword="Nothing"/> or an empty string.
    ''' </exception>
    ''' 
    ''' <exception cref="FileNotFoundException">
    ''' Thrown if the specified shortcut file does not exist.
    ''' </exception>
    ''' 
    ''' <exception cref="InvalidOperationException">
    ''' Thrown if the underlying Shell API call fails to commit the removal.
    ''' </exception>
    ''' 
    Public Shared Sub ClearAppUserModelId(shortcutPath As String)
            If String.IsNullOrEmpty(shortcutPath) Then
                Throw New ArgumentNullException(NameOf(shortcutPath))
            End If
            If Not File.Exists(shortcutPath) Then
                Throw New FileNotFoundException($"The specified shortcut file is not found: {shortcutPath}", shortcutPath)
            End If

            Dim propertyStoreObj As Object = Nothing
            Dim propertyStore As IPropertyStore = Nothing
            Dim propVariant As New PropVariantNative()

            Try
                Dim iid As Guid = IID_IPropertyStore
                Dim hr As Integer = SHGetPropertyStoreFromParsingName(shortcutPath, IntPtr.Zero, GPS_READWRITE, iid, propertyStoreObj)
                If hr <> 0 Then
                    Throw New Win32Exception(hr, $"SHGetPropertyStoreFromParsingName failed with HRESULT 0x{hr:X8}.")
                End If

                propertyStore = DirectCast(propertyStoreObj, IPropertyStore)

                ' A zero-initialized PROPVARIANT has vt = VT_EMPTY (0), which signals
                ' "remove this property from the store".
                propVariant.vt = 0US
                propVariant.wReserved1 = 0US
                propVariant.wReserved2 = 0US
                propVariant.wReserved3 = 0US
                propVariant.pointerValue = IntPtr.Zero

                Dim key As PropertyKey = PKEY_AppUserModel_ID
                propertyStore.SetValue(key, propVariant)
                propertyStore.Commit()

            Catch ex As Exception
                Throw New InvalidOperationException($"Failed to clear AppUserModelID from shortcut: {shortcutPath}", ex)

            Finally
                If propertyStore IsNot Nothing AndAlso Marshal.IsComObject(propertyStore) Then
                    Marshal.FinalReleaseComObject(propertyStore)
                End If

#Disable Warning IDE0059 ' Unnecessary assignment of a value
                propertyStore = Nothing
                propertyStoreObj = Nothing
#Enable Warning IDE0059 ' Unnecessary assignment of a value
                GC.Collect()
                GC.WaitForPendingFinalizers()
                GC.Collect()
            End Try
        End Sub

    ''' 
    ''' <summary>
    ''' Enumerates every application registered under the Windows <c>shell:AppsFolder</c> virtual folder
    ''' and returns its display name together with its <c>AppUserModelID</c>.
    ''' <para></para>
    ''' This is the native equivalent of the PowerShell <c>Get-StartApps</c> cmdlet.
    ''' </summary>
    ''' 
    ''' <returns>
    ''' A list of <see cref="InstalledAppInfo"/> entries, one per registered application that exposes an
    ''' <c>AppUserModelID</c>. The list is empty if no application is found.
    ''' </returns>
    ''' 
    ''' <exception cref="InvalidOperationException">
    ''' Thrown if the enumeration of <c>shell:AppsFolder</c> fails.
    ''' </exception>
    ''' 
    Public Shared Function GetInstalledAppUserModelIds() As List(Of InstalledAppInfo)
            Dim result As New List(Of InstalledAppInfo)()

            Dim appsFolderObj As Object = Nothing
            Dim appsFolder As IShellItem = Nothing
            Dim enumObj As Object = Nothing
            Dim enumItems As IEnumShellItems = Nothing

            Try
                Dim iidShellItem As Guid = IID_IShellItem
                SHCreateItemFromParsingName("shell:AppsFolder", IntPtr.Zero, iidShellItem, appsFolderObj)
                appsFolder = DirectCast(appsFolderObj, IShellItem)

                Dim bhid As Guid = BHID_EnumItems
                Dim iidEnum As Guid = IID_IEnumShellItems
                appsFolder.BindToHandler(IntPtr.Zero, bhid, iidEnum, enumObj)
                enumItems = DirectCast(enumObj, IEnumShellItems)

                Do
                    Thread.CurrentThread.Join(0)

                    Dim item As IShellItem = Nothing
                    Dim fetched As UInteger = 0UI
                    Dim hr As Integer = enumItems.Next(1UI, item, fetched)

                    If hr <> 0 OrElse fetched = 0UI OrElse item Is Nothing Then
                        Exit Do
                    End If

                    Dim item2 As IShellItem2 = Nothing
                    Try
                        item2 = DirectCast(item, IShellItem2)

                        Dim appIdValue As String = Nothing
                        Try
                            Dim keyAppId As PropertyKey = PKEY_AppUserModel_ID
                            item2.GetString(keyAppId, appIdValue)
                        Catch comEx As COMException When comEx.ErrorCode = E_ELEMENTNOTFOUND
                            appIdValue = Nothing
                        End Try

                        Dim nameValue As String = Nothing
                        Try
                            ' SIGDN_NORMALDISPLAY = 0
                            item2.GetDisplayName(0UI, nameValue)
                        Catch
                            nameValue = String.Empty
                        End Try

                        If Not String.IsNullOrEmpty(appIdValue) Then
                            result.Add(New InstalledAppInfo(If(nameValue, String.Empty), appIdValue))
                        End If

                    Finally
                        If item IsNot Nothing AndAlso Marshal.IsComObject(item) Then
                            Marshal.FinalReleaseComObject(item)
                        End If
                    End Try
                Loop

                Return result

            Catch ex As Exception
                Throw New InvalidOperationException("Failed to enumerate installed AppUserModelIDs from shell:AppsFolder.", ex)

            Finally
                If enumItems IsNot Nothing AndAlso Marshal.IsComObject(enumItems) Then
                    Marshal.FinalReleaseComObject(enumItems)
                End If
                If appsFolder IsNot Nothing AndAlso Marshal.IsComObject(appsFolder) Then
                    Marshal.FinalReleaseComObject(appsFolder)
                End If
            End Try
        End Function

#End Region

    End Class

#End Region
