' NOTE: THIS CLASS WAS AI-GENERATED BY CLAUDE (OPUS 4.6)
'
' MODIFICATIONS MAY BE REALIZED IN FUTURE VERSIONS OF THIS APPLICATION TO CLEAN AI ARTIFACTS AND IMPROVE CODE QUALITY,
' BUT NO GUARANTEE IS MADE ON THE MAINTENANCE OF THIS CLASS.

#Region " Option Statements "

Option Strict On
Option Explicit On
Option Infer Off

#End Region

#Region " Imports "

Imports System.ComponentModel
Imports System.Drawing.Design
Imports System.Windows.Forms.Design

Imports DevCase.Core.IO

#End Region

#Region " ShortcutFileInfoAppIdEditor "

Namespace DevCase.Core.Design

    ''' ----------------------------------------------------------------------------------------------------
    ''' <summary>
    ''' Provides a dropdown <see cref="UITypeEditor"/> that lists every installed
    ''' <c>AppUserModelID</c> available on the system (equivalent to the PowerShell
    ''' <c>Get-StartApps</c> cmdlet), sorted alphabetically by display name,
    ''' with a leading <c>&lt;None&gt;</c> entry to clear the value.
    ''' </summary>
    ''' ----------------------------------------------------------------------------------------------------
    Friend NotInheritable Class ShortcutFileInfoAppIdEditor : Inherits UITypeEditor

        ''' ----------------------------------------------------------------------------------------------------
        ''' <summary>
        ''' Sentinel display text used to represent a null / unset <c>AppUserModelID</c>.
        ''' </summary>
        ''' ----------------------------------------------------------------------------------------------------
        Private Const NoneDisplayText As String = "<None>"

        ''' ----------------------------------------------------------------------------------------------------
        ''' <summary>
        ''' Gets the editor style used by the <see cref="EditValue"/> method.
        ''' </summary>
        ''' ----------------------------------------------------------------------------------------------------
        ''' <param name="context">
        ''' A type descriptor context.
        ''' </param>
        ''' ----------------------------------------------------------------------------------------------------
        ''' <returns>
        ''' <see cref="UITypeEditorEditStyle.DropDown"/>.
        ''' </returns>
        ''' ----------------------------------------------------------------------------------------------------
        Public Overrides Function GetEditStyle(context As ITypeDescriptorContext) As UITypeEditorEditStyle
            Return UITypeEditorEditStyle.DropDown
        End Function

        ''' ----------------------------------------------------------------------------------------------------
        ''' <summary>
        ''' Displays a dropdown <see cref="ListBox"/> populated with every installed
        ''' <c>AppUserModelID</c> and returns the one selected by the user.
        ''' </summary>
        ''' ----------------------------------------------------------------------------------------------------
        ''' <param name="context">
        ''' A type descriptor context.
        ''' </param>
        ''' 
        ''' <param name="provider">
        ''' A service provider used to obtain the <see cref="IWindowsFormsEditorService"/>.
        ''' </param>
        ''' 
        ''' <param name="value">
        ''' The current value of the property being edited.
        ''' </param>
        ''' ----------------------------------------------------------------------------------------------------
        ''' <returns>
        ''' The new <c>AppUserModelID</c> selected by the user, or <see langword="Nothing"/>
        ''' if the user picked the <c>&lt;None&gt;</c> entry.
        ''' </returns>
        ''' ----------------------------------------------------------------------------------------------------
        Public Overrides Function EditValue(context As ITypeDescriptorContext,
                                            provider As IServiceProvider,
                                            value As Object) As Object

            If provider Is Nothing Then
                Return value
            End If

            Dim editorService As IWindowsFormsEditorService =
                DirectCast(provider.GetService(GetType(IWindowsFormsEditorService)), IWindowsFormsEditorService)

            If editorService Is Nothing Then
                Return value
            End If

            Dim currentValue As String = TryCast(value, String)

            Dim apps As List(Of InstalledAppInfo)
            Try
                apps = ShortcutAppIdHelper.GetInstalledAppUserModelIds()
            Catch
                apps = New List(Of InstalledAppInfo)()
            End Try

            Dim sortedApps As List(Of InstalledAppInfo) =
                apps.OrderBy(Function(a As InstalledAppInfo) a.DisplayName,
                             StringComparer.CurrentCultureIgnoreCase).ToList()

            Dim listBox As New ListBox() With {
                .BorderStyle = BorderStyle.None,
                .IntegralHeight = False,
                .Height = 260,
                .Width = 420,
                .HorizontalScrollbar = True
            }

            ' Leading sentinel item for clearing the value.
            Dim noneItem As New AppIdListItem(NoneDisplayText, Nothing)
            listBox.Items.Add(noneItem)

            Dim selectedItem As AppIdListItem = noneItem

            Dim app As InstalledAppInfo
            For Each app In sortedApps
                Dim item As New AppIdListItem($"{app.DisplayName}   —   {app.AppUserModelId}", app.AppUserModelId)
                listBox.Items.Add(item)
                If currentValue IsNot Nothing AndAlso
                   String.Equals(currentValue, app.AppUserModelId, StringComparison.Ordinal) Then
                    selectedItem = item
                End If
            Next app

            ' If the current value isn't in the enumerated list, still preselect <None>.
            listBox.SelectedItem = selectedItem

            ' Close the dropdown when the user clicks an item.
            Dim clickHandler As EventHandler =
                Sub(sender As Object, e As EventArgs)
                    editorService.CloseDropDown()
                End Sub
            AddHandler listBox.Click, clickHandler

            ' Close on Enter; cancel on Escape.
            Dim keyHandler As KeyEventHandler =
                Sub(sender As Object, e As KeyEventArgs)
                    If e.KeyCode = Keys.Enter Then
                        editorService.CloseDropDown()
                        e.Handled = True
                    ElseIf e.KeyCode = Keys.Escape Then
                        listBox.SelectedItem = Nothing
                        editorService.CloseDropDown()
                        e.Handled = True
                    End If
                End Sub
            AddHandler listBox.KeyDown, keyHandler

            Try
                editorService.DropDownControl(listBox)
            Finally
                RemoveHandler listBox.Click, clickHandler
                RemoveHandler listBox.KeyDown, keyHandler
            End Try

            Dim picked As AppIdListItem = TryCast(listBox.SelectedItem, AppIdListItem)
            If picked Is Nothing Then
                Return value ' User cancelled: keep the original value.
            End If

            ' Return String.Empty (not Nothing) when <None> is picked, so the
            ' PropertyGrid reliably propagates the change to the setter.
            Return If(picked.AppUserModelId, String.Empty)
        End Function

        ''' ----------------------------------------------------------------------------------------------------
        ''' <summary>
        ''' Represents a single entry in the dropdown <see cref="ListBox"/>,
        ''' pairing a display text with its associated <c>AppUserModelID</c> payload.
        ''' </summary>
        ''' ----------------------------------------------------------------------------------------------------
        Private NotInheritable Class AppIdListItem

            Public ReadOnly Property DisplayText As String
            Public ReadOnly Property AppUserModelId As String

            Public Sub New(displayText As String, appUserModelId As String)
                Me.DisplayText = displayText
                Me.AppUserModelId = appUserModelId
            End Sub

            Public Overrides Function ToString() As String
                Return Me.DisplayText
            End Function

        End Class

    End Class

End Namespace

#End Region